import 'package:flutter/painting.dart';

import '../level_config.dart';
import 'level_2.dart' show workshopTheme;
import 'level_4.dart' show neonTheme;

const _reward = 210;

final List<LevelConfig> mechanicTutorialLevels = [
  LevelConfig(
    id: 11,
    tapChoiceProfile: TapChoiceProfile.narrow,
    name: 'Ramp Lesson',
    hint: 'The ramp turns a falling ball into a sideways hit.',
    theme: workshopTheme,
    baseReward: _reward,
    generationTemplate: 'ramp-intro',
    generationDifficulty: 1,
    complexityScore: 1,
    objects: [
      ObjectSpec.platform(2.0, 9.3, 3.8),
      ObjectSpec.box(0.85, 9.3, starter: true, push: const Offset(14, 0)),
      ...ObjectSpec.dominoRow(
        fromX: 1.45,
        surfaceY: 9.3,
        count: 4,
        spacing: 0.5,
      ),
      ObjectSpec.ball(3.55, 9.3),
      ObjectSpec.ramp(5.0, 13.55, 2.4, angle: 0.28),
      ObjectSpec.target(7.8, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 12,
    name: 'The Teeter Bridge',
    hint:
        'Tap the plank itself and predict how far its first swing will carry it.',
    theme: neonTheme,
    baseReward: _reward,
    generationTemplate: 'plank-intro',
    generationDifficulty: 2,
    complexityScore: 2,
    objects: [
      ObjectSpec.plank(
        3.8,
        kGroundY,
        length: 2.0,
        starter: true,
        push: const Offset(8, 0),
      ),
      ObjectSpec.target(5.7, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 13,
    tapChoiceProfile: TapChoiceProfile.exact,
    name: 'Switch First',
    hint: 'The ball presses the switch; the open gate clears its route.',
    theme: workshopTheme,
    baseReward: _reward,
    generationTemplate: 'switch-gate-intro',
    generationDifficulty: 3,
    complexityScore: 3,
    objects: [
      ...ObjectSpec.dominoRow(
        fromX: 1.2,
        surfaceY: kGroundY,
        count: 4,
        spacing: 0.56,
        firstIsStarter: true,
      ),
      ObjectSpec.ball(3.43, kGroundY),
      ObjectSpec.button(
        4.35,
        kGroundY - 0.12,
        id: 'switch-13',
        linkedTargetId: 'gate-13',
      ),
      ObjectSpec.gate(5.2, kGroundY - 0.8, id: 'gate-13'),
      ObjectSpec.target(6.6, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 14,
    tapChoiceProfile: TapChoiceProfile.narrow,
    name: 'Catapult Cat',
    hint: 'The ball wakes the cat; the cat carries the chain forward.',
    theme: neonTheme,
    baseReward: _reward,
    generationTemplate: 'cat-intro',
    generationDifficulty: 4,
    complexityScore: 4,
    objects: [
      ...ObjectSpec.dominoRow(
        fromX: 1.2,
        surfaceY: kGroundY,
        count: 4,
        spacing: 0.56,
        firstIsStarter: true,
      ),
      ObjectSpec.ball(3.43, kGroundY),
      ObjectSpec.cat(4.21, kGroundY, direction: 1),
      ObjectSpec.target(7.2, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 15,
    tapChoiceProfile: TapChoiceProfile.narrow,
    name: 'Dog Run',
    hint: 'Start on the right: the dog runs left through the dominoes.',
    theme: workshopTheme,
    baseReward: _reward,
    generationTemplate: 'dog-intro',
    generationDifficulty: 5,
    complexityScore: 5,
    objects: [
      ObjectSpec.domino(
        6.0,
        kGroundY,
        starter: true,
        push: const Offset(-0.35, 0),
      ),
      ObjectSpec.domino(5.44, kGroundY),
      ObjectSpec.domino(4.88, kGroundY),
      ObjectSpec.domino(4.32, kGroundY),
      ObjectSpec.ball(3.75, kGroundY),
      ObjectSpec.dog(2.95, kGroundY, direction: -1),
      ObjectSpec.target(0.8, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 16,
    tapChoiceProfile: TapChoiceProfile.narrow,
    name: 'Gate Timing',
    hint: 'The switch is ahead of the barrier. Predict when the gate opens.',
    theme: neonTheme,
    baseReward: _reward,
    generationTemplate: 'switch-gate-sequence',
    generationDifficulty: 6,
    complexityScore: 6,
    objects: [
      ObjectSpec.box(1.0, kGroundY, starter: true, push: const Offset(14, 0)),
      ...ObjectSpec.dominoRow(
        fromX: 1.7,
        surfaceY: kGroundY,
        count: 4,
        spacing: 0.56,
      ),
      ObjectSpec.ball(4.5, kGroundY),
      ObjectSpec.button(
        5.05,
        kGroundY - 0.12,
        id: 'switch-16',
        linkedTargetId: 'gate-16',
      ),
      ObjectSpec.gate(5.9, kGroundY - 0.8, id: 'gate-16'),
      ObjectSpec.target(7.4, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 17,
    tapChoiceProfile: TapChoiceProfile.narrow,
    name: 'The Upward Handoff',
    hint: 'The upper row feeds a leftward launch from the floor spring.',
    theme: workshopTheme,
    baseReward: _reward,
    generationTemplate: 'springboard-handoff',
    generationDifficulty: 7,
    complexityScore: 7,
    objects: [
      ObjectSpec.platform(6.2, 9.2, 4.8),
      ObjectSpec.box(8.1, 9.2, starter: true, push: const Offset(-14, 0)),
      ...ObjectSpec.dominoRow(
        fromX: 7.55,
        surfaceY: 9.2,
        count: 4,
        spacing: -0.42,
      ),
      ObjectSpec.ball(5.45, 9.2),
      ObjectSpec.jumper(3.0, kGroundY, direction: -1),
      ObjectSpec.target(1.9, kGroundY, radius: 0.65),
    ],
  ),
  LevelConfig(
    id: 18,
    tapChoiceProfile: TapChoiceProfile.narrow,
    name: 'The Teeter Transfer',
    hint:
        'Tip the plank across the floor; its far end knocks the ball toward the target.',
    theme: neonTheme,
    baseReward: _reward,
    generationTemplate: 'plank-sweep-transfer',
    generationDifficulty: 8,
    complexityScore: 8,
    objects: [
      ObjectSpec.plank(
        2.0,
        kGroundY,
        length: 2.0,
        starter: true,
        push: const Offset(8, 0),
      ),
      ...ObjectSpec.dominoRow(
        fromX: 3.5,
        surfaceY: kGroundY,
        count: 3,
        spacing: 0.56,
      ),
      ObjectSpec.ball(5.5, kGroundY),
      ObjectSpec.target(7.6, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 19,
    tapChoiceProfile: TapChoiceProfile.broad,
    name: 'Drop Into the Relay',
    hint:
        'The high run drops the ball onto a dog, then the cat opens the low gate.',
    theme: workshopTheme,
    baseReward: _reward,
    generationTemplate: 'drop-pet-gate',
    generationDifficulty: 9,
    complexityScore: 9,
    objects: [
      ObjectSpec.platform(2.2, 8.8, 4.0),
      ObjectSpec.box(0.8, 8.8, starter: true, push: const Offset(14, 0)),
      ...ObjectSpec.dominoRow(
        fromX: 1.4,
        surfaceY: 8.8,
        count: 4,
        spacing: 0.5,
      ),
      ObjectSpec.ball(3.6, 8.8),
      ObjectSpec.dog(7.2, kGroundY, direction: 1),
      ObjectSpec.cat(8.0, kGroundY, direction: 1),
      ObjectSpec.button(
        8.35,
        kGroundY - 0.12,
        id: 'switch-19',
        linkedTargetId: 'gate-19',
      ),
      ObjectSpec.gate(8.85, kGroundY - 0.8, id: 'gate-19'),
      ObjectSpec.target(9.25, kGroundY, radius: 0.48),
    ],
  ),
  LevelConfig(
    id: 20,
    tapChoiceProfile: TapChoiceProfile.narrow,
    name: 'Lever Before the Gate',
    hint:
        'The plank presses the switch first; its falling end then sends the ball through the open gate.',
    theme: neonTheme,
    baseReward: _reward,
    generationTemplate: 'plank-switch-gate',
    generationDifficulty: 10,
    complexityScore: 10,
    objects: [
      ObjectSpec.plank(
        2.0,
        kGroundY,
        length: 2.2,
        starter: true,
        push: const Offset(8, 0),
      ),
      ObjectSpec.button(
        4.2,
        kGroundY - 0.12,
        id: 'switch-20',
        linkedTargetId: 'gate-20',
      ),
      ObjectSpec.gate(5.1, kGroundY - 0.8, id: 'gate-20'),
      ObjectSpec.ball(5.8, kGroundY),
      ObjectSpec.domino(6.5, kGroundY),
      ObjectSpec.domino(7.05, kGroundY),
      ObjectSpec.target(8.3, kGroundY, radius: 0.48),
    ],
  ),
];
